# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
warnings_are_errors: true
sudo: false
cache: packages

before_install:
  - Rscript -e 'if (!requireNamespace("BiocManager", quietly = TRUE)){install.packages("BiocManager")}; BiocManager::install(c("phyloseq"), ask = FALSE)'

r_github_packages:
  - r-lib/covr
  - bryandmartin/corncob

after_success:
  - Rscript -e 'covr::codecov()'

env:
  - _R_S3_METHOD_LOOKUP_BASEENV_AFTER_GLOBALENV_=true
  - _R_S3_METHOD_LOOKUP_USE_TOPENV_AS_DEFENV_=true

addons:
  apt:
    packages:
      - libgit2-dev
